### ISSUE TITLE
Support Quilt

### ISSUE THREAD

**Issue by Carterpersall** [JamCoreModding/RightClickHarvest#11]
https://quiltmc.org/

There seems to be multiple issues with using RightClickHarvest with Quilt:
 - Fabric is listed as a dependency, causing a crash if used in Quilt
 - Both RightClickHarvest and JamLib do not work with Quilt Standard Libraries (replacement for Fabric API), latest.log will be given below
 
I'm not sure how deep this issue goes, but it might be worth looking into as many people are moving over to quilt.

latest.log:
```
[22:40:13] [main/INFO]: Loading Minecraft 1.19 with Quilt Loader 0.17.0-beta.4
[22:40:13] [main/INFO]: Loading 42 mods:
	- jamlib 0.0.8
	- java 17
	- minecraft 1.19
	- qsl_biome_testmod 1.0.0
	- qsl_dimension_testmod 1.0.0
	- qsl_item_setting_testmod 1.0.0
	- qsl_testmod 1.0.0
	- quilt_base 2.0.0-beta.3+1.19
	- quilt_base_testmod 1.0.0
	- quilt_biome 2.0.0-beta.3+1.19
	- quilt_block_extensions 2.0.0-beta.3+1.19
	- quilt_block_extensions_testmod 1.0.0
	- quilt_block_testmod 1.0.0
	- quilt_client_command 2.0.0-beta.3+1.19
	- quilt_client_command_testmod 1.0.0
	- quilt_command 2.0.0-beta.3+1.19
	- quilt_command_testmod 1.0.0
	- quilt_core_testmod 1.0.0
	- quilt_crash_info 2.0.0-beta.3+1.19
	- quilt_crash_info_testmod 1.0.0
	- quilt_data_testmod 1.0.0
	- quilt_dimension 2.0.0-beta.3+1.19
	- quilt_gui_testmod 1.0.0
	- quilt_item_group 2.0.0-beta.3+1.19
	- quilt_item_group_testmod 1.0.0
	- quilt_item_setting 2.0.0-beta.3+1.19
	- quilt_item_testmod 1.0.0
	- quilt_lifecycle_events 2.0.0-beta.3+1.19
	- quilt_lifecycle_events_testmod 1.0.0
	- quilt_loader 0.17.0-beta.4
	- quilt_management_testmod 1.0.0
	- quilt_networking 2.0.0-beta.3+1.19
	- quilt_networking_testmod 1.0.0
	- quilt_registry 2.0.0-beta.3+1.19
	- quilt_registry_testmod 1.0.0
	- quilt_resource_loader 2.0.0-beta.3+1.19
	- quilt_resource_loader_testmod 1.0.0
	- quilt_screen 2.0.0-beta.3+1.19
	- quilt_screen_testmod 1.0.0
	- quilt_tooltip 2.0.0-beta.3+1.19
	- quilt_tooltip_testmod 1.0.0
	- rightclickharvest 2.0.8
[22:40:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Carter%20Persall/Desktop/Server/Test%20Server/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Quilt Env=SERVER
[22:40:16] [main/INFO]: Compatibility level set to JAVA_16
[22:40:16] [main/INFO]: Compatibility level set to JAVA_17
[22:40:16] [main/WARN]: Reference map 'JamLib-refmap.json' for jamlib.mixins.json could not be read. If this is a development environment you can ignore this message
[22:40:18] [main/INFO]: Building unoptimized datafixer
[22:40:19] [main/INFO]: Testing EventTests...
[22:40:19] [main/WARN]: Event phase ordering conflict detected.
Event phase quilt:b1 is ordered both before and after event phase quilt:b3.
[22:40:19] [main/INFO]: Event unit tests succeeded in 62 milliseconds.
[22:40:19] [main/INFO]: Testing EventListenAllTests...
[22:40:19] [main/INFO]: Event#listenAll successfully refused registration of listener for event testGenericEventBlock
[22:40:19] [main/INFO]: Tested test event.
[22:40:19] [main/INFO]: Hello object rose_bush.
[22:40:19] [main/INFO]: Hello from networking user!
[22:40:19] [main/INFO]: [Quilt Command] Networking support is enabled
[22:40:19] [main/INFO]: Block Block{quilt_registry_test_events:event_test_block} id=quilt_registry_test_events:event_test_block raw=934 was registered in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: Block Block{quilt_registry_test_monitors_registration:test_block_a} id=quilt_registry_test_monitors_registration:test_block_a raw=935 was registered in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: [forAll event]: Block Block{quilt_registry_test_monitors_registration:test_block_a} id=quilt_registry_test_monitors_registration:test_block_a raw=935 had its registration monitored in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: Block Block{quilt_registry_test_monitors_registration:test_block_b} id=quilt_registry_test_monitors_registration:test_block_b raw=936 was registered in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: [forAll event]: Block Block{quilt_registry_test_monitors_registration:test_block_b} id=quilt_registry_test_monitors_registration:test_block_b raw=936 had its registration monitored in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: Block Block{quilt_registry_test_monitors:test_block_a} id=quilt_registry_test_monitors:test_block_a raw=937 was registered in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: [forAll event]: Block Block{quilt_registry_test_monitors:test_block_a} id=quilt_registry_test_monitors:test_block_a raw=937 had its registration monitored in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: Block Block{quilt_registry_test_monitors:test_block_b} id=quilt_registry_test_monitors:test_block_b raw=938 was registered in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: [forAll event]: Block Block{quilt_registry_test_monitors:test_block_b} id=quilt_registry_test_monitors:test_block_b raw=938 had its registration monitored in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: [forUpcoming event]: Block Block{quilt_registry_test_monitors:test_block_b} id=quilt_registry_test_monitors:test_block_b raw=938 had its registration monitored in registry Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)]
[22:40:19] [main/INFO]: Initializing RightClickHarvest...
[22:40:19] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jamlib'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.0-beta.4.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.0-beta.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.0-beta.4.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/lifecycle/v1/ServerTickEvents
	at io.github.jamalam360.jamlib.JamLib.onInitialize(JamLib.java:40) ~[jam-lib-0.0.8.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.0-beta.4.jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.github.jamalam360.jamlib.JamLib.onInitialize(JamLib.java:40) ~[jam-lib-0.0.8.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.0-beta.4.jar:?]
	... 16 more
```

**Comment by Jamalam360** [comment]
Haha, oh no! The irony is I'm a massive Quilt supporter and I'm on one of their development teams!

Anyways, I believe the problem is you are on Minecraft 1.19, but Quilted Fabric API is not available for that version yet.

Quilted Fabric API is usually bundled with Quilt Standard Libraries and is used to fill in the gaps that QSL is currently missing with Fabric API.

The mods should work on 1.18.2 with Quilt according to my testing.

**Comment by Carterpersall** [comment]
I was using a 1.19 dev build from github actions (https://github.com/QuiltMC/quilt-standard-libraries/actions/runs/2468912518). It's still possible that the current 1.19 build is still broken and that's causing my issue.

**Comment by Jamalam360** [comment]
No, you were using a Dev build of QSL, not of QFAPI. Quilted Fabric API is required, and is not yet released for 1.19.

**Comment by Carterpersall** [comment]
Ah gotcha, I'll close this issue.

**Comment by Jamalam360** [comment]
o7
